openapi: '3.0.0'
info:
  version: '1.0.0'
  title: 'Arch Lab Example API'
  description: Пример API для первого домашнего задания по курсу Архитектура программных систем
servers:
  - url: http://localhost:8080
    description: Message Server
paths:
  /chat/searchByUserId:
    get:
      summary: Поиск чата по id пользователя
      parameters:
      - name: userId
        description: id пользователя
        in: query
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Чаты в которых состоит пользователь
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/сhats'
        500:
          description: Ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /chat/searchByChatId:
    get:
      summary: Поиск чата по id пользователя
      parameters:
      - name: chatId
        description: id чата
        in: query
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Чат
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/сhat'
        404:
          description: Нет чата с запрашиваемым id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /chat:
    post:
      summary: Создание чата
      parameters:
      - name: chatName
        description: название чата
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Чат
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/chat_id'
        500:
          description: Ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /chat/addMember:
    post:
      summary: Добавление пользователя в чат
      parameters:
      - name: chatId
        description: id чата
        in: query
        required: true
        schema:
          type: integer
      - name: userId
        description: id пользователя
        in: query
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Пустое сообщение
        500:
          description: Ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /message:
    post:
      summary: Добавление сообщения в чат
      parameters:
      - name: chatId
        description: id чата
        in: query
        required: true
        schema:
          type: integer
      - name: text
        description: текст сообщения
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: id добавленного сообщения
          content:
            application/json:
              schema:
                type: object
                required:
                  - id
                properties:
                  id:
                    type: integer
        500:
          description: Ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    get:
      summary: Получение сообщений из чата
      parameters:
      - name: chatId
        description: id чата
        in: query
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Сообщения из чата
          content:
            application/json:
              schema:
                type: object
                required:
                  - chatId
                  - messages
                properties:
                  chatId:
                    type: integer
                  messages:
                    type: array
                    items:
                      type: object
                      required:
                        - chat_id
                        - id
                        - message
                        - user_id
                      properties:
                        chat_id:
                          type: integer
                        id:
                          type: integer
                        message:
                          type: string
                        user_id:
                          type: integer
        500:
          description: Ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    message_id:
      description: Идентификатор сообщенимя пользователя
      type: integer
    user_id:
      description: Уникальный идентификатор пользователя
      type: string
    chat_id:
      description: Идентификатор чата
      type: integer
    users:
      type: array
      items:
        $ref: '#/components/schemas/user'
    сhats:
      type: array
      items:
        $ref: '#/components/schemas/сhat'
    сhat:
      type: object
      required:
        - creator_id
        - id
        - name
      properties:
        id: 
          $ref: '#/components/schemas/chat_id'
        creator_id:
          $ref: '#/components/schemas/user_id'
        name:
          description: Название чата
          type: string
    user:
      type: object
      required:
        - id
        - first_name
        - last_name
        - email
        - title
        - login
        - password
      properties:
        id:
          type: integer
        uuid:
          $ref: '#/components/schemas/user_id'
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        title:
          type: string
        login:
          type: string
        password:
          type: string
    Error:
      type: object
      required:
        - message
      properties:
        message:
          description: Сообщение о ошибке
          type: string
  securitySchemes:
      basicAuth:     
        type: http
        scheme: basic
security:
  - basicAuth: []